{% set version="0.5.9" %}

package:
  name: ipython-cluster-helper
  version: {{ version }}

source:
  fn: ipython-cluster-helper-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipython-cluster-helper/ipython-cluster-helper-{{ version }}.tar.gz
  md5: 234227ee9262c5dcb43134c5ef4de9c2

build:
  number: 3

requirements:
  build:
    - python
    - setuptools
    - netifaces

  run:
    - python
    - ipyparallel >=4.0
    - zeromq
    - pyzmq
    - netifaces
    - libgcc

test:
  imports:
    - cluster_helper.cluster

about:
  home: https://github.com/roryk/ipython-cluster-helper
  license: MIT
  summary: Tool to easily start up an IPython cluster on different schedulers
