package:
  name: ngs_utils
  version: "{{ load_setup_py_data().get('version') }}"

source:
  git_rev: master
  git_url: https://github.com/vladsaveliev/NGS_Utils

build:
  number: 15

requirements:
  build:
    - python
    - pip
    - setuptools >=18.5
    - numpy
  run:
    - python
    - bedtools
    - sambamba
    - htslib
    # pip packages:
    - cython
    - numpy
    - pyyaml
    - simplejson
    - joblib
    - ipython-cluster-helper
    - pysam
    - pybedtools
    - gffutils
    - jinja2
    - beautifulsoup4
    - lxml
    - xlsxwriter >=0.5.5
    - nose

test:
  imports:
    - ngs_utils.file_utils
    - tab_utils

about:
  home: https://github.com/vladsaveliev/NGS_Utils
  license: GPLv3
