{% set version=load_setup_py_data().get('version') %}

package:
  name: ngs_utils
  version: "{{ version }}"

source:
  git_url: https://github.com/vladsaveliev/NGS_Utils
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python
    - pip
    - numpy
    - six
  run:
    - python
    - bedtools >=2.25
    - sambamba
    - htslib
    # pip packages:
    - cython
    - numpy
    - six
    - pyyaml
    - simplejson
    - joblib
    - ipython-cluster-helper
    - pysam
    - pybedtools
    - jinja2
    - beautifulsoup4
    - lxml
    - xlsxwriter >=0.5.5
    - nose

test:
  imports:
    - ngs_utils.file_utils
    - ngs_utils.reference_data
    - tab_utils

about:
  home: https://github.com/vladsaveliev/NGS_Utils
  license: GNU General Public License v3 (GPLv3)
  summary: 'Helper function for NGS projects by Vlad Saveliev'
  license_family: GPL3
